spring:
  datasource:
    url: jdbc:h2:mem:oauth2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          #          google:
          #            client-id: your-google-client-id
          #            client-secret: your-google-client-secret
          #            scope: profile, email
          #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: Ov23li3GQfwzS8l3ycOF
            client-secret: ed4435e8b96c26c531b66036787657f8b2135d1e
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

